services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat_db

    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    networks:
      - chat-network

  ai-service:
    build:
      context: ./ai-service
    restart: always

    environment:
      - PORT=7001
      - DB_HOST=porto_sister-db
      - DB_USER=sister
      - DB_PASSWORD=Jancok1337!
      - DB_NAME=sisterdb
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - db
    networks:
      - chat-network

  api-gateway:
    build:
      context: ./api-gateway
    restart: always

    environment:
      - PORT=7000
      - DB_HOST=porto_sister-db
      - DB_USER=sister
      - DB_PASSWORD=Jancok1337!
      - DB_NAME=sisterdb
      - AI_SERVICE_URL=http://ai-service:7001
      - GATEWAY_API_KEY=Ab8RN6JMBztWn_bxD6sZjww_S9a7rpevSwZJEysRwHQSo9kPrQ
    depends_on:
      - db
      - ai-service
    networks:
      - chat-network

  app:
    build:
      context: ./client
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chatai.rule=Host(`porto-chatai-sister.rryxja.easypanel.host`)"
      - "traefik.http.services.chatai.loadbalancer.server.port=80"
    networks:
      - chat-network
      - easypanel

volumes:
  db_data:

networks:
  chat-network:
    driver: bridge
  easypanel:
    external: true
